### PR TITLE
Split up docs and make them pretty

### PR DESCRIPTION
**Pull request by rgrams**
Whew. Hopefully I didn't miss anything...or...didn't miss _too many_ things.

### CODE REVIEW

**Comment by d954mas** [comment]
Cool, thanks.

**Comment by d954mas** [comment]
What you think about make api format like in other defold extensions.
https://github.com/britzl/monarch/blob/master/README_API.md

**Comment by d954mas** [comment]
## monarch.hide(screen_id, [callback])
Hide a screen that has been shown using the `no_stack` option. If used on a screen that was shown without the `no_stack` option it will only hide it if the screen is on top of the stack and the behavior will be exactly like if `monarch.back()` had been called. This operation will be added to the queue if Monarch is busy.

**PARAMETERS**
* `screen_id` (string|hash) - Id of the screen to hide.
* `callback` (function) - Optional function to call when the screen has been hidden.

**RETURN**
* `success` (boolean) - True if the process of hiding the screen was started successfully.

**Comment by d954mas** [comment]
Also i think, adding horizontal line after every function make it more readable)

**Comment by d954mas** [comment]
---
#### Box2dDistanceJoint:SetLength(length)
Set the rest length

**PARAMETERS**
* `length` <kbd>number</kbd>

**RETURN**
* <kbd>number</kbd> - Clamped rest length

---
#### Box2dDistanceJoint:GetMinLength()
Get the minimum length

**RETURN**
* <kbd>number</kbd>

**Comment by rgrams** [comment]
Alright, how's that?

**Comment by d954mas** [comment]
Cool:) I like how it look

Thanks.

**Comment by d954mas** [comment]
Is it ready for merge?

**Comment by rgrams** [comment]
Yup, ready.

I'm sure there will be some mistakes, but I am done for a while. :)

**Pull request merged**
